language: node_js
node_js:
  - "stable"
cache:
  directories:
  - "node_modules"
branches:
  only:
    - master

env:
  - WEBPACK_VERSION=4

script: npm run build

deploy:
  - provider: pages
    edge: true
    local-dir: dist
    target-branch: gh-pages
    github-token: $GH_TOKEN
    skip-cleanup: true
    on:
      tags: true
