language: node_js
node_js:
  - "stable"
cache:
  directories:
  - "node_modules"
branches:
  only:
    - master

#env:
#  - WEBPACK_VERSION=4
#install:
#  # Use npm 5.7.x since it has introduced `npm ci`
#  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
#  - npm install -g sass node-sass html-minifier
#  - npm ci

script: npm run build

deploy:
  - provider: pages
    edge: true
    local-dir: dist
    target-branch: gh-pages
    github-token: $GH_TOKEN
    skip-cleanup: true
    on:
      tags: true
