# Stages

stages:
  - test
  - build
  - deploy
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

script:
  - npm run test:unit
  - npm run build

deploy:
  - provider: pages
    edge: true
    local-dir: dist
    target-branch: gh-pages
    github-token: $GH_TOKEN
    skip-cleanup: true
    on:
      tags: true
      branch: master
